# Generated by Django 5.2.8 on 2025-11-21 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='category',
            field=models.CharField(choices=[('EDUCATION', 'Education'), ('CERTIFICATE', 'Certificate'), ('PROJECT', 'Project'), ('COMPETITION', 'Competition'), ('PUBLICATION', 'Publication'), ('AWARD', 'Award'), ('RESEARCH', 'Research'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
